### ISSUE TITLE
make-anthology.sh shouldn't generate bib files

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#14]
`make-anthology.sh` currently creates this structure:

```bash
anthology/
  P/
    P19/
      P19.xml
      P19-1001.pdf
      P19-1001.bib
      P19-1001.Supplementary.tgz
```

The `*.bib` files are no longer needed since we only use the XML at ingestion time.

**Comment by davidweichiang** [comment]
The .bib files are used during .xml generation, so it is actually more work to remove them than to leave them. Also, maybe it would be good to archive them in case something goes wrong with the conversion to XML?

**Comment by mjpost** [comment]
Sure, it doesn't hurt to have them.
