### ISSUE TITLE
Add SIG information

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#15]
SIG information is available (I think?) in the `meta` file. This should be added as a tag in the XML so that it is available to automatically be added the Anthology at ingestion time (saving the manual effort and error associated with it).

**Comment by mjpost** [comment]
Update: I think the `meta` line has to be added to START.

**Comment by rrgerber** [comment]
Please elaborate on what exactly we should do on START.

**Comment by mjpost** [comment]
Hi Rich—

Two pieces for the "CDROM" tab:

1. It would be nice to have a "sig" field, where people could enter associated SIGs. This would get written to the "meta" file in a sig line, e.g.,

       sig sigparse

<img width="786" alt="image" src="https://user-images.githubusercontent.com/455256/65104722-7906e300-d9a0-11e9-8a04-36c12f33117a.png">

Then we could modify ACLPUB to add this automatically at ingestion. Currently, I have to do it manually for all workshops.

2. Additionally, the examples for chairs aren't good. As above, you can see that it shows

       Rada Mihalcea (U of M)

We can't easily parse this into "last name, first name". It's easy to strip out the affiliation, but if a name has three parts, we have to resort to heuristics to determine which is first / last. It would be helpful if the examples listed instead the following format:

       Mihalcea, Rada

**Comment by rrgerber** [comment]
Implemented this and updated the version accordingly
