### ISSUE TITLE
add “sig” tag to output

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#18]
this has been added to the meta file, should be added to the xml so that the anthology can ingest it automatically

**Comment by mjpost** [comment]
#15 added a `sig` tag to the meta file. We should add this to the XML file that is ingested by the Anthology. Currently, this is hard, because:

- `anthologize/anthologize.pl` generates the PDFs and BibTeX files using the `meta` file
- `anthologize/anthology_xml.py` then takes those bibs and generates an XML file

`anthology_xml.py` does not have access to the `meta` file. A simple solution would be to copy it, which might be good since we'd also like to add a `<shortbooktitle> field (acl-org/anthology#567). We could then update the script to output that data in the `<meta>` block of the XML. I'm not sure if there's a better way.

**Comment by davidweichiang** [comment]
Would it be bad to add `sig` and `shortbooktitle` as extra fields in the BibTeX?

**Comment by mjpost** [comment]
That’s a good approach. Extracting the info would proceed the same way we do for the book title then.

**Comment by mjpost** [comment]
I'm closing this, since this is quite easy to handle in the Anthology now with #28.
