### ISSUE TITLE
Add option to add DOIs to the footer stamp

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#21]
This could be enabled for ACL only events, since we only pay for DOIs for them.

**Comment by danielgildea** [comment]
There is code in place to do this, which was used for ACL 2017.

manage-db.pl sets a tex variable \DOIcounter for each paper.
This variable needs to be referenced in the file citation-stamp.tex for the DOI to be included
in the footer.

**Comment by davidweichiang** [comment]
The code for adding the submission id (https://github.com/davidweichiang/pdfstamp) originally broke links too, but we found a way to preserve them (the lines about "named destinations"). I wonder if the same would work in `pdfunderneath.py`.

**Comment by danielgildea** [comment]
How about including instructions how to update citation-stamp.tex, including using the DOI, in the new documentation?

**Comment by danielgildea** [comment]
The links to files such as citation-stamp.tex from the new documentation
https://acl-org.github.io/ACLPUB/start.html
are broken -- though it sounds like @rrgerber is going to add them back to the repository.

https://github.com/acl-org/ACLPUB/commit/6a168ed91e99755e385361d6b46682813ce8cefd

**Comment by mjpost** [comment]
Ah, yes, it would be good to add these back in so that they are tracked.

Unfortunately, we have repurposed `/templates` to hold the conference paper templates. Maybe we could move them to `/templates/proceedings` or something like that? Or a top-level `/proceedings`?

**Comment by rrgerber** [comment]
Hi there, I am sorry that I got lost in this thread.  Yes, I want to add the templates back into the repo, but if the planned location is different then please let me know.

**Comment by danielgildea** [comment]
Let's go with `/templates/proceedings`.

**Comment by mjpost** [comment]
Sounds good to me.

**Comment by mjpost** [comment]
I just noticed that `bin/manage-db.pl` uses these templates and assumes `/templates`, so we'll have to adjust a few paths. @rrgerber, if you want to add these back in on a branch under `/templates/proceedings`, I can help update the script.

**Comment by rrgerber** [comment]
I will add to templates/proceedings and change the /bin code as needed.  It also requires changing START.  I will attend to this within the next few days.

**Comment by mjpost** [comment]
Sounds good—Thanks, Rich.

**Comment by rrgerber** [comment]
This is done.  Closing.
