### ISSUE TITLE
Remove HTML generation code?

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/ACLPUB#3]
Quite a few pieces of ACLPUB are dedicated to generation of HTML, but as far as I know, this code is not actually used any more. Is it?

For example, the proceedings.tgz generated for EMNLP 2018 contains only one HTML file, advertisement.html, which is a list of accepted papers. I believe that @desilinguist did not rely on this HTML file when making the EMNLP 2018 web page (because I think I gave him a Markdown version) and wonder whether anyone else uses it.

Assuming that the HTML generated here is not used anymore, I suggest retiring all relevant code (advertisement.pl authors.pl db-to-html.pl index.pl program-html.pl unified-authors.pl) so that all HTML generation is done from the Anthology (which @mbollmann is working on a modern version of).

**Comment by mjpost** [comment]
This functionality more properly belongs in [acl-pub](https://github.com/acl-org/acl-pub) and could be removed from here, but we should make sure that the current round of pub chairs, at least, since we might be interrupting something. Tagging the ones whose handles I could find:

- NAACL: @slukin, Alla Roskovskaya
- ACL: @ivulic, @kgimpel, Douwe Kiela, Shay Cohen

**Comment by slukin** [comment]
@desilinguist and I just discussed this the other day actually: 

From EMNLP 2018, he was expecting .csv files with the author index, session chair information, anthology paper id mappings, and abstracts. I do not know the script that was used to create these .csv files for him, so we decided for this year that Nitin would write his own scraper from these .html files that live in the cdom/ generated part of the proceedings.tgz (authors.html, index.html, and program.html). 

@davidweichiang, if there is another way to obtain this information/create these .csv relevant files without using these .html files, it's fine to remove that code from our perspective, if we can have that code to create the .cvs files either be generated directly when we pull the proceedings.tgz or run after it's been pulled.

**Comment by davidweichiang** [comment]
Hm, the plot thickens. I think I would suggest (if @desilinguist has not written this scraper already) that these .csv files be generated straight from the db, meta, and abstracts files, which are plain text and simpler to deal with than HTML. That would smooth the road to removing HTML generation from ACLPUB.

However, the db, meta, and abstracts files will contain TeX control sequences. I would suggest, if it's practical, that Nitin's scraper use the same TeX-to-XML/HTML code that @mbollmann is writing for the Anthology. Is that possible?

(Currently, there are about a half-dozen pieces of code across three Git repositories that do this same task, and each covers a different subset of TeX. I'm hoping that they can be unified into one really good one.)

**Comment by slukin** [comment]
Here is some information from Nitin: "The only .csv file I created via scraping was anthology-mapping.csv. The rest were provided to me by the EMNLP program chairs. I haven't started to work on any script yet." He also said that the anthology-mapping.csv was created by scraping one of these .html files.

So it seems we can shift towards removing the html generation to directly generate the files into an easier-to-read format, like separate .csv files or a single YAML file that can be parsed (a suggestion from Nitin). For a concrete example, the .csv files that Nitin used for EMNLP are here: https://github.com/emnlp2018/emnlp2018.github.io/tree/master/scripts/data

**Comment by davidweichiang** [comment]
I think that sounds good. But I'm still unsure how to get all the different pieces of the system to share code when possible.

(When I tag @desilinguist does he see it, or does he have to be connected to the repository somehow?)

**Comment by desilinguist** [comment]
I am the current owner of the `acl-org` organization so I see everything. Bwahahaha. Sorry :)

**Comment by rrgerber** [comment]
I would suggest leaving the HTML generation code in, since it is very useful for people to download the "all" target and check that everything is OK by looking at the CD rom directory.
