### ISSUE TITLE
generating new ID format in cdrom/ layout

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#31]
I am confused about ACLPUB is run and wonder if anyone can answer questions here.

The `proceedings.tgz` files I've received from pubchairs (say for ACL 2019) have a layout like this:

    papers/
      proceedings/
        cdrom/
          pdf/
            P19-1001.pdf
            P19-1002.pdf
            ...

i.e., the actual paper IDs. However, I can't see where this is produced. It should be in [bin/bib.pl](https://github.com/acl-org/ACLPUB/blob/master/bin/bib.pl), but that code does not produce the full Anthology ID, but rather something like

    papers/
      proceedings/
        cdrom/
          pdf/
            naacl00.pdf
            naacl01.pdf
            naacl02.pdf
            ...

See for example [lines 150–152 of bib.pl](https://github.com/acl-org/ACLPUB/blob/5d4469840cf987bb365d4474d09158f3efb17baf/bin/bib.pl#L150), where the bib file name is created:

```perl
  my $fn_base = sprintf "%0${digits}d", $pn;
  my $fn = "cdrom/bib/$abbrev$fn_base.bib";
  open(FILE,"> $fn") || printf(STDERR "Can't open $fn: $!\n");
```

Indeed, this is the format I've received recently when people have built this manually. So it seems to be an issue just with START. 

Can anyone clarify what START is doing here? How is `cdrom/pdf` getting populated with the actual Anthology files?

**Comment by danielgildea** [comment]
I think that the piece of code that you are looking for is here:

https://github.com/acl-org/ACLPUB/blob/master/bin/manage-db.pl#L567

**Comment by mjpost** [comment]
Thanks, Dan. But I think that just produces files with names like "acl007.pdf", not "P19-1007.pdf" (`$abbrev` here is read directly from the `meta` file, and `$papnum_formatted` is just a 0-padded paper ID).

```perl
	system("export PYTHONPATH $ENV{PYTHONPATH}; $ENV{ACLPUB}/bin/pdfunderneath.py $file ./cd.pdf -o cdrom/pdf/$abbrev$papnum_formatted.pdf")==0 || die;
```

**Comment by mjpost** [comment]
I think I will update `bib.pl` and `manage-db.pl` to generate the new format directly. Maybe Softconf is doing something in post-processing, but they'll have to adapt this, anyway.

**Comment by danielgildea** [comment]
Oh, I see.  Maybe this is what you are looking for?

https://github.com/acl-org/ACLPUB/blob/master/anthologize/anthologize.pl#L97

Generating with the right name in the first place does seem like a good idea.

**Comment by mjpost** [comment]
That one generates a file outside the `proceedings/`, in the `anthology/` directory that amalgamates all workshops and volumes within a conference. 

But for the past year, the `proceedings.tgz` tarballs that pub chairs have delivered to me have the correct file names under `cdrom/pdf`. I'm starting to think the code for that must be within START.

**Comment by rrgerber** [comment]
This is Rich.   Regarding these IDs, we don't do anything outside of the ACLPUB code.  The only place where START comes in is the entry of the base url for the bibtex citations.  

Matt, if you haven't do this already, could you push all the recent changes into start branch.  

Also, could you post one message with all changes required in START?  I've been swamped with mail recently, and have not been following this discussion as closely as I should be.

**Comment by mjpost** [comment]
Ah, I figured it out! Book chairs have been adding this as the `abbrev` field in the meta file:

> abbrev N19-1

Someone must have started that convention and then it got picked up.

@rrgerber when this is all ready and tested, I'll merge into the "start" branch and will add a set of instructions of things we need changed. Thank you!

**Comment by mjpost** [comment]
Hi @rrgerber,

Please see #29. It is all in one place.

matt
