### ISSUE TITLE
\textasciitilde

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#41]
We often see `ñ` converted to something like `\\textasciitilde {n}`, e.g., the following from EAMT 2020:

```bibtex
author = "Gema Ram\'{\i}rez-S\'{a}nchez and Jaume Zaragoza-Bernabeu and Marta Ba\\textasciitilde {n}\'{o}n and Sergio Ortiz Rojas",
```

It's possible this is caused by ACLPUB.

**Comment by rrgerber** [comment]
This code is not in ACLPUB, and those characters would have been inputted in native utf-8.  I don't know how they do things on EasyChair, but the pub chairs must have manually added that tex code to the files used by ACLPUB.  There is no such conversion done in the aclpub package.

**Comment by mjpost** [comment]
Yep, Dan found and fixed it in easy2acl: https://github.com/acl-org/easy2acl/commit/70706ab4a43f60e998099b5c2a74c1d7fef7d5ee.
