### ISSUE TITLE
bad bibkeys

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#47]
ACLPUB seems sometimes to create bad bib keys when there are special characters in the lead author's name:

```bibtex
@InProceedings{b\"{u}ler-etal-2005-using,
  author    = "B\"{u}ler, Dirk and Minker, Wolfgang and Elciyanti, Artha",
```

**Comment by danielgildea** [comment]
seems like there is code to prevent this from happening

https://github.com/acl-org/ACLPUB/blob/master/bin/bib.pl#L119

is it possible that the file was created in 2005 and that the problem has since been fixed?

**Comment by mjpost** [comment]
Ah, okay. It was created recently, but I wonder if the assembler used an older version of the code. There were a few other mistakes, too. Thanks for looking.
