### ISSUE TITLE
Local copies of template no longer say DO NOT DISTRIBUTE

### ISSUE THREAD

**Issue by aryamccarthy** [acl-org/ACLPUB#60]
With the shift to stamping the paper number in START, the top line of the template has been removed. This used to read something like "ACL Submission XYZ. DO NOT DISTRIBUTE."

Now that that's been removed, local copies don't have this warning. I think it's useful to include this, though. If you share your own paper with others, e.g. requesting feedback, you don't have to 'opt-in' to telling them not to distribute further. It's automatically done.

The right place to put it, I think, is in the title block, just below "Anonymous ACL Submission".

**Comment by rrgerber** [comment]
This has nothing to do with ACLPUB, but rather with the latex and Word templates distributed by the program chairs, linked to in the call for papers.  The ACLPUB package is for post-acceptance publication, and there was never such a stamp on papers in the proceedings, which are (and are even encouraged to be) distributed as widely as possible.

**Comment by aryamccarthy** [comment]
Hi Rich, it's related to the template files in this repo. The .sty file forms the basis of the templates distributed by program chairs.

These are the templates I'm referring to: https://github.com/acl-org/ACLPUB/blob/master/templates/latex/acl.sty

**Comment by rrgerber** [comment]
Oh, OK.  I guess you should go ahead and change it then.  But I am not the person who should change it, since we don't use those templates.

**Comment by mjpost** [comment]
@aryamccarthy Do you want to do a PR?
