### ISSUE TITLE
Is the ACL 2020 format the same as EMNLP 2022

### ISSUE THREAD

**Issue by sharan21** [acl-org/ACLPUB#78]
My paper draft is done over the ACL 2020 format (identical to the ACL 2022 format apparently) and I want to submit this paper to EMNLP 2022. Will this be an issue? Both templates look the same but I am afraid it will get a desk rejection because of wrong format. Please let me know if this would most likely be the case. Thanks!

**Comment by rrgerber** [comment]
This is Rich Gerber at softconf.com.  You have posted your comment in the wrong place.  The people in charge of the EMNLP conference are at emnlp2022pcs@gmail.com.  While the templates have slightly changed, the changes will be of no importance for the paper reviewer, and will not be desk rejected.  If your paper is accepted, then use the new templates for your final paper.
