### ISSUE TITLE
Two Questions About Signing the Transfer Copyright PDF

### ISSUE THREAD

**Issue by ChristLBUPT** [acl-org/ACLPUB#83]
Hello, I'm submitting a paper to ACL2024 Findings.  I'm requested to sign the acl-copyright-transfer-2021.pdf
 located at `templates/copyright/acl-copyright-transfer-2021.pdf`. I have two following questions:

- Which language should be used for signatures? English or the language the author speaks?

- Among the three cases of signing (_All authors signing, Work for company, One author signing_) if I'm an MS. student as well as an intern from a company (part of my authors are from the company), while my affiliation is my college in the paper is my school, which one should I tick on? _Work for company_ or _One author signing_?

**Comment by mjpost** [comment]
Typically transactions like these are done in English.

Regarding signing, it's not a question of your listed affiliations, but a question of who owns the work. If it was funded by an internship, it's likely owned by the company that paid you (a "work for hire").

**Comment by ChristLBUPT** [comment]
> Typically transactions like these are done in English.
> 
> Regarding signing, it's not a question of your listed affiliations, but a question of who owns the work. If it was funded by an internship, it's likely owned by the company that paid you (a "work for hire").

I see, thanks a lot!
